version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: "S3_ACCESS_KEY"
    secretkey: "S3_SECRET_KEY"
    region: "S3_REGION"
    bucket: "S3_BUCKET"
auth:
  token:
    realm: https://auth.import.pw/auth
    service: "Docker registry"
    issuer: "import.pw auth server"
    rootcertbundle: "/etc/auth-cert.pem"
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
